#:schema node_modules/wrangler/config-schema.json
name = "cyber-gift-charity-market"
compatibility_date = "2024-05-12"
pages_build_output_dir = "./build/client"
compatibility_flags = [ "nodejs_compat" ]